stages:
  - test
  - performances
  - build
  - frontend
  - deploy

test:
    stage: test
    image: mkenney/npm
    script:
        - npm install
        - npm update
        - ng test
        - echo "performances tests"

performances:
   stage: performances
   image: mkenney/npm
   script:
       - echo "performances tests"

build:
  stage: build
  script: echo "Building the app"

frontend:
  stage: frontend
  script: echo "Frontend check"

deploy_staging:
  stage: deploy
  script: echo "Deploy to staging server"
