stages:
  - test
  - performances
  - build
  - frontend
  - deploy

test:
    stage: test
    image: mkenney/npm
    script:
        - npm install
        # - ng test
        - echo "performances tests"

performances:
   stage: performances
   image: mkenney/npm
   script:
       - echo "performances tests"

build:
  stage: build
  script: echo "Building the app"

frontend:
  stage: frontend
  script: echo "Frontend check"

deploy_staging:
  stage: deploy
  image: guikingone/front_prod_env
  only:
      - master
  script:
      - ssh-add <(echo "$DEPLOY_SERVER_KEY")
      - ssh -p22 server_user@server_production_ip "mkdir /home/usr/$MAIN_USER/$PROJECT_NAME"
      - echo "Deploy to staging server"
