stages:
  - test
  - performances
  - build
  - deploy

test:
    stage: test
    image: guikingone/front_env
    before_script:
        - npm install
    script:
        - echo "performances tests"

performances:
   stage: performances
   image: guikingone/front_env
   before_script:
       - npm install
   script:
       - echo "performances tests"

build:
  stage: build
  before_script:
      - npm install
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  image: guikingone/front_env
  only:
      - master
  before_script:
      - mkdir -p ~/.ssh
      - eval $(ssh-agent -s)
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
      - npm install
  script:
      - echo "Deploy to production server"
      - ssh-add <(echo "$SERVER_AUTHENTICATION_KEY")
      - ssh -p22 server_user@server_ip "mkdir /home/user/$SERVER_OWNER/$PROJECT_NAME"
